### ISSUE TITLE
Bad file format in inputdata 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/MOSART#33]
File inputdata/rof/mosart/MOSART_routing_0.125nldas2_c190415.nc
is netCDF-4 and unreadable on cheyenne.

**Comment by ekluzek** [comment]
We do run a test for this on cheyenne and it has been passing. SMS_Ld1.nldas2_rnldas2_mnldas2.I2000Ctsm50NwpSpNldasGs.cheyenne_gnu.clm-default.  So for example see:

/glade/p/cgd/tss/ctsm_baselines/ctsm1.0.dev105/SMS_Ld1.nldas2_rnldas2_mnldas2.I2000Ctsm50NwpSpNldasGs.cheyenne_gnu.clm-default/TestStatus

@jedwards4b and @mvertens it seems like this should be fixed for the CESM2.2.0 release. Let me know if you disagree, otherwise I'll add a new tag for MOSART to the testdb. Should we just fix this issue, or bring in the nuopc changes that also need to happen?

**Comment by ekluzek** [comment]
Fixed in mosart1_0_37
