### ISSUE TITLE
Remove setting of MOSART_MODE from buildnml

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/MOSART#48]
In mosart1_0_44 I added an awkward change where MOSART_MODE gets set in buildnml.

Some comments on this are here:

https://github.com/ESCOMP/MOSART/pull/46#issuecomment-958116418

We need to decide on a better solution and bring that in when we can.

**Comment by billsacks** [comment]
@ekluzek - I never addressed your initial question about having this in buildlib vs. buildnml. Since `CLM_ACCELERATED_SPINUP` is defined in env_run.xml, it feels wrong to have some dependence on it in buildlib, since then changes after building wouldn't be captured. So I think buildnml is better than buildlib, but both seem problematic.

**Comment by ekluzek** [comment]
Ahhh yes. One problem is actually that MOSART_MODE is in env_build, but CLM_ACCELERATED_SPINUP is in env_run. So neither way is technically correct. But, you could argue that since MOSART_MODE is env_build it should be in buildlib. And I suppose we could move CLM_ACCELERATED_SPINUP in env_build as well. But, I still agree that neither way is good here. I do think putting it in env_build removes the potential order dependence issue that you brought up though.

We'll talk more about this tomorrow. I hope we can come up with something that feels better all around.
